### Практическое задание к уроку 2
#### Методичка 3

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;  
   В данном случае произведения матриц $AB$ и $BA$ не определены:  
       - в случае $AB$ - количество столбцов матрицы $A=2$, а количество строк матрицы $B=4$  
       - в случае $BA$ - количество столбцов матрицы $B=2$, а количество строк матрицы $A=4$  
     
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;  
   Определено только произведение матриц $AB$. Размерность полученной матрицы будет равна $2 \times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;  
   Определены оба произведения $AB$ и $BA$. Размерности полученных матриц будут равны $AB: 8 \times 8$ и $BA: 3 \times 3$, т.е крадратные матрицы 8 и 3 порядков соответственно.  
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.  
   Определены оба произведения $AB$ и $BA$. Получится 2 квадратные матрицы 4 порядка.

__2.__ Найти сумму и произведение матриц 
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A+B=\begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}$$

$$A\cdot B=\begin{pmatrix}
1\cdot 4+(-2)\cdot 0 & 1\cdot (-1)+(-2)\cdot 5 \\
3\cdot 4+0\cdot 0 & 3\cdot (-1)+0\cdot 5
\end{pmatrix}=\begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}$$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A:\n{A}')
print(f'Матрица B:\n{B}')

Матрица A:
[[ 1 -2]
 [ 3  0]]
Матрица B:
[[ 4 -1]
 [ 0  5]]


In [3]:
print(f'A+B:\n{A+B}')
print(f'A*B:\n{np.dot(A, B)}')

A+B:
[[ 5 -3]
 [ 3  5]]
A*B:
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A=\begin{pmatrix}
3 & 21 \\
9 & -18
\end{pmatrix}\,\,\,
-2B=\begin{pmatrix}
0 & -10 \\
-4 & 2
\end{pmatrix}\,\,\,
4C=\begin{pmatrix}
8 & -16 \\
4 & 4
\end{pmatrix}$$

$$3A-2B+4C=\begin{pmatrix}
11 & -5 \\
9 & -12
\end{pmatrix}$$

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица A:\n{A}')
print(f'Матрица B:\n{B}')
print(f'Матрица C:\n{C}')

Матрица A:
[[ 1  7]
 [ 3 -6]]
Матрица B:
[[ 0  5]
 [ 2 -1]]
Матрица C:
[[ 2 -4]
 [ 1  1]]


In [5]:
print(f'3A-2B+4C:\n{3*A-2*B+4*C}')

3A-2B+4C:
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.  

$$A^T=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$$

$$A\cdot A^T=\begin{pmatrix}
4\cdot 4+1\cdot 1 & 4\cdot 5+1\cdot(-2) & 4\cdot 2+1\cdot 3 \\
5\cdot4+(-2)\cdot 1 & 5\cdot 5+(-2)\cdot(-2) & 5\cdot 2+(-2)\cdot 3 \\
2\cdot 4+3\cdot1 & 2\cdot 5+3\cdot(-2) & 2\cdot 2+3\cdot 3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$$

$$A^T\cdot A=\begin{pmatrix}=
4\cdot 4+5\cdot 5+2\cdot 2 & 4\cdot 1+5\cdot (-2)+2\cdot 3 \\
1\cdot 4+(-2)\cdot 5+3\cdot 2 & 1\cdot 1+(-2)\cdot(-2)+3\cdot 3
\end{pmatrix}=\begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}$$

In [6]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица A:\n{a}')
print(f'Транспонированная матрица A:\n{a.T}')

Матрица A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица A:
[[ 4  5  2]
 [ 1 -2  3]]


In [7]:
print(f'A*A^T:\n{np.dot(a, a.T)}')
print(f'A^T*A:\n{np.dot(a.T, a)}')

A*A^T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A^T*A:
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [8]:
# Вариант 1. Перемножение двух произвольных матриц используя numpy array
def matrix_multiply1(a, b):
    assert a.shape[1] == b.shape[0], "A's columns count isn't equals to B's rows count!"
    n = a.shape[0]
    b_transposed = b.T
    c = np.zeros([n, n])
    for i in range(n):
        for j in range(n):
            c[i, j] = (a[i] * b_transposed[j]).sum()
    return c

In [9]:
A_1 = np.array([[1, 0], [2, 1], [10, 5]])
B_1 = np.array([[2, 0, 0], [0, 0, 1]])
C_1 = matrix_multiply1(A_1, B_1)
print(f'Матрица A:\n{A_1}')
print(f'Матрица B:\n{B_1}')
print(f'Матрица A*B:\n{C_1}')

Матрица A:
[[ 1  0]
 [ 2  1]
 [10  5]]
Матрица B:
[[2 0 0]
 [0 0 1]]
Матрица A*B:
[[ 2.  0.  0.]
 [ 4.  0.  1.]
 [20.  0.  5.]]


In [10]:
# Вариант 2. Перемножение двух произвольных матриц полностью без использования numpy
def matrix_multiply2(a, b):
    a_shape = [len(A), len(A[0])]
    b_shape = [len(B), len(B[0])]

    assert a_shape[1] == b_shape[0], "A's columns count isn't equals to B's rows count!"
    
    n = a_shape[0]
    
    b_t = [[0 for _ in range(b_shape[0])] for _ in range(b_shape[1])]
    for j in range(b_shape[1]):
        for i in range(b_shape[0]):
            b_t[j][i] = B[i][j]
    
    c = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            c[i][j] = A[i][0] * b_t[j][0] + A[i][1] * b_t[j][1]
    return c

In [11]:
A_2 = [[1, 0], [2, 1], [10, 5]]
B_2 = [[2, 0, 0], [0, 0, 1]]
C_2 = matrix_multiply2(A, B)
print('Матрица A:', *A_2, sep='\n')
print('Матрица B:', *B_2, sep='\n')
print('Матрица A*B:', *C_2, sep='\n')

Матрица A:
[1, 0]
[2, 1]
[10, 5]
Матрица B:
[2, 0, 0]
[0, 0, 1]
Матрица A*B:
[14, -2]
[-12, 21]


#### Методичка 4

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=\sin^2 x+cos^2 x=1$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4 \cdot 5 \cdot 9=180$$
Определитель треугольной матрицы равен произведению элементов ее главной диагонали.
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=45+84+96-105-72-48=0$$

In [12]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель матрицы A: {np.linalg.det(a)}')

Определитель матрицы A: 180.0


In [13]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель матрицы B: {np.linalg.det(b):.1f}')

Определитель матрицы B: -0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})=det(A)\cdot det(A)=4*4=16$, т.к возведение в квадрат - это по сути произведение матрицы саму на себя, то по свойству определятеля для квадратных матриц одинакого размера $det(AB)=det(A)\cdot det(B)$
    
   б) $det(A^{T})=4$, т.к. определитель транспонированной матрицы равен определителю исходной;
    
   в) $det(2A)=4\cdot 2^n$, где $n$ - это порядок матрицы. По свойству "Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число" получается, что мы умножаем каждую строку/столбец на 2 $n$ раз.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
вырожденная.

Для этого найду ее определитель:  
$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}=364-126-84+126-364+84=0$$
Т.к определитель матрицы равен нулю, то это значит, что данная матрица вырожденная.

In [14]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель матрицы A: {np.linalg.det(A)}')

Определитель матрицы A: 0.0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$
Строка 3 является суммой строк 1 и 2. Следовательно отбрасываю 3 строку.
$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$
Вычту из первой строки вторую.
$$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1
\end{pmatrix}$$
Больше преобразований произвести не могу, следовательно ранг данной матрицы равен 2.

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$
Вычитаю из второй строки первую, а из третьей - первую, умноженную на два.
$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$
Меняю местами первую и последнюю строки, а потом еще первую и четвертую.
$$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 1
\end{pmatrix}$$
Вычитаю из четвертой строки третью и выбрасываю получившуюся нулевую строку.
$$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1
\end{pmatrix}$$
Больше преобразований произвести не могу, следовательно ранг данной матрицы равен 3.

In [15]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы A: {np.linalg.matrix_rank(A)}')

Ранг матрицы A: 2


In [16]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Ранг матрицы B: {np.linalg.matrix_rank(B)}')

Ранг матрицы B: 3
