### Практическое задание к уроку 4
#### Методичка 6

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Т.к. количество неизвестных меньше коиев равнений, то система будет иметь бесконечное множество решений.  
Записываю систему линейных уравнений в виде расширенной матрицы:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0 \\
-2 \\
4
\end{matrix}
\end{pmatrix}$$

Преобразую расширенную матрицу путем элементарных преобразований. Умножаю 1 строку на -2 и склаываю её с 2-й, умножаю 1 строку на -1 и складываю её с 3-й:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
0 & -1 & 1 & 5 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0 \\
-2 \\
4
\end{matrix}
\end{pmatrix}$$

Записываю получившуюся матрицу опять в виде системы:
$$\begin{cases}
x_1+x_2-x_3-2x_4=0 \\
~~~~-x_2+x_3+5x_4=-2 \\
~~~~~~~~~~-2x_3+3x_4=4
\end{cases}$$

Выражаю $x_3$ через $x_4$. После этого нахожу значения $x_2$ и $x_1$:  
$$-2x_3=4-3x_4\,\,\, \rightarrow\,\,\, x_3=1.5x_4-2$$
$$-x_21.5x_4-2+5x_4=-2\,\,\, \rightarrow \,\,\, x_2=6.5x_4$$
$$x_1+6.5x_4-1.5x_4+2-2x_4=0\,\,\,\rightarrow\,\,\, x_1+3x_4+2=0\,\,\,\rightarrow\,\,\, x_1=-3x_4-2$$

Подставляю получившиеся значения переменных в изначальную систему уравнений для проверки:  
$$\begin{cases}
-3x_4-2+6.5x_4-1.5x_4+2-2x_4=0 \\
-6x_4-4+6.5x_4-1.5+2+x_4=-2 \\
-3x_4-2+6.5x_4-4.5x_4+6+x_4=4
\end{cases}\,\,\,\,\, \Rightarrow\,\,\,\,\, \begin{cases}
0=0\\
-2=-2\\
4=4
\end{cases}$$
__После подстановки получил тождества. Следовательно полученное общее решение - верное.__

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

In [1]:
import numpy as np
import scipy.linalg

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$  
Т.к. $r(A)=r(A|B)$, то данная система уравнений совместна. А т.к. $r(A)=n$, то она имеет 1 решение.

In [2]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a_ext = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
b = np.array([4, -17, 0])
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}\nРанг расширенной матрицы: {np.linalg.matrix_rank(a_ext)}')
print(f'Корни системы уравнений: {scipy.linalg.solve(a, b)}')

Ранг матрицы: 3
Ранг расширенной матрицы: 3
Корни системы уравнений: [1. 2. 3.]


   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$  
Т.к. $r(A) \neq r(A|B)$, то данная система уравнений не совместна, следоательно не имеет решений.

In [3]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
a_ext = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 9]])
b = np.array([1, -2, 9])
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}\nРанг расширенной матрицы: {np.linalg.matrix_rank(a_ext)}')

Ранг матрицы: 1
Ранг расширенной матрицы: 2


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$  
Т.к. $r(A)=r(A|B)$, то данная система уравнений совместна. А т.к. $r(A)<n$, то она имеет бесконечное множество решений.

In [4]:
a = np.array([[1, 2, 5], [3, 1, -8]])
a_ext = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
b = np.array([4, -2])
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}\nРанг расширенной матрицы: {np.linalg.matrix_rank(a_ext)}')

Ранг матрицы: 2
Ранг расширенной матрицы: 2


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Ранг матрицы равен рангу расширенной матрицы $r(A)=r(A|B)=4$, следовательно даннаяматрицы совместна. Т,к. ранг матрицы равен числу линейных уравнений (чилу строк) $r(A)=n=4$, то она имеет 1 решение.

In [5]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
a_ext = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
b = np.array([3, 2, 4, 1])
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}\nРанг расширенной матрицы: {np.linalg.matrix_rank(a_ext)}')
print(f'Корни системы уравнений: {scipy.linalg.solve(a, b)}')

Ранг матрицы: 4
Ранг расширенной матрицы: 4
Корни системы уравнений: [2.76666667 0.3        1.33333333 0.5       ]


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.  
  
Система уравнений является несовместной, если ранг матрицы не равен рангу расширенной матрицы $r(A) \neq r(A|B)$. Выполню элементаные преобразования, чтобы найти ранг матрицы. Умножу 1 строку на -4 и сложу ее с 2-й, а потом умножу 1 строку на -7 и сложу ее с 3-й:  
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}=$$

Умножу 2 строку на -2 и сложу ее с третьей:  
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a-3(b-4a)
\end{matrix}
\end{pmatrix}$$

Ранг матрицы $r(A)=2$. Чтобы система уравнений являлась несовместной небоходимо, чтобы выражение $c-7a-3(b-4a)=5a-3b+c \neq 0$.

#### Методичка 7

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$  

Нахожу определитель матрицы, а также определители $detA_{1}$ и $detA_{2}$:  
$$detA=\begin{vmatrix}
1 & -2 \\
3 & -4
\end{vmatrix}= 1\cdot(-4)-3\cdot(-2)=-4+6=2$$
$$detA_1=\begin{vmatrix}
1 & -2 \\
7 & -4
\end{vmatrix}= 1\cdot(-4)-7\cdot(-2)=-4+14=10$$
$$detA_2=\begin{vmatrix}
1 & 1 \\
3 & 7
\end{vmatrix}= 1\cdot 7-3\cdot 1=4$$
$$x_1=\frac{detA_1}{detA}=\frac{10}{2}=5,\,\,\, x_2=\frac{detA_2}{detA}=\frac{4}{2}=2$$
Подставляю получившиеся значения в исходную систему уравнений для проверки:  
$$\begin{cases}
5-4=1 \\
15-8=7
\end{cases}$$
Получились тождества, следовательно корни найдены верно.

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$  

Нахожу определитель матрицы, а также определители $detA_{1}$, $detA_{2}$ и $detA_{3}$: 
$$detA=\begin{vmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix}=2\cdot 1\cdot 1+1\cdot 4\cdot 5+2\cdot (-1)\cdot (-3)-2\cdot 1\cdot 5-2\cdot 4\cdot (-3) -1\cdot 1\cdot (-1)=2+20+6-10+24+1=43$$
$$detA_1=\begin{vmatrix}
10 & -1 & 5 \\
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix}=10\cdot 1\cdot 1+1\cdot (-1)\cdot (-3)+5\cdot 4\cdot (-2)-1\cdot 1\cdot 5-10\cdot 4\cdot (-3)-1\cdot (-1)\cdot (-2)=$$
$$=10+3-40-5+120-2=86$$
$$detA_2=\begin{vmatrix}
2 & 10 & 5 \\
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix}=2\cdot (-2)\cdot 1+10\cdot (-3)\cdot 2+1\cdot 1\cdot 5-5\cdot (-2)\cdot 2-1\cdot 10\cdot 1-2\cdot (-3)\cdot 1=-4-60+5+20-10+6=-43$$
$$detA_4=\begin{vmatrix}
2 & -1 & 10 \\
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix}=2\cdot 1\cdot 1+2\cdot (-1)\cdot (-2)+1\cdot 4\cdot 10-2\cdot 1\cdot 10-1\cdot (-1)\cdot 1-2\cdot 4\cdot (-2)=2+4+40-20+1+16=43$$
$$x_1=\frac{86}{43}=2,\,\,\, x_2=\frac{-43}{43}=-1,\,\,\, x_3=\frac{43}{43}=1$$
Подставляю получившиеся значения в исходную систему уравнений для проверки:  
$$\begin{cases}
4+1+5=10 \\
2-1-3=-2 \\
4-4+1=1
\end{cases}$$
Получились тождества, следовательно корни найдены верно.

_2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
Домножаю 1 строку на 2 и вычитаю её из 1-й. Затем умножаю 1 строку на 3 и вычитаю ее из 3-й. 
$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$$

Домножаю 2 строку на 4 и вычитаю её из 3-й.  
$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

In [6]:
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 0]])
np.dot(L, U)

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 28]])

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

Домножаю 1 строку на 2 и вычитаю её из 2-й. Затем домножаю 1 строку на 3 и вычитаю её из 3-й. После этого домнажаю 1 строку на 4 и вычитаю её из 4-й.  
$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$$

Домножаю 2 строку на 5 и вычитаю её из 3-й. Потом домножаю 2 строку на 6 и вычитаю её из 4-й.
$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix}$$

Домножаю 3 строку на 7 и вычитаю её из 4-й.
$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

In [7]:
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
np.dot(L, U)

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Представляю систему уравнений в виде матрицы.  
$$\begin{pmatrix}
2 & 1 & 3 \\
11 & 7 & 5 \\
9 & 8 & 4
\end{pmatrix}$$

Домножаю 1 строку на $\frac{11}{2}$ и вычитаю её из 2-й. Затем домножаю 1 строку на $\frac{9}{2}$ и вычитаю её из 3-й
$$\begin{pmatrix}
2 & 1 & 3 \\
0 & \frac{3}{2} & -\frac{23}{2} \\
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 \\
\frac{11}{2} & 1 & 0 \\
\frac{9}{2} & l_{32} & 1
\end{pmatrix}$$

Домножаю 2 строку на $\frac{7}{3}$ и вычитаю её из 3-й.
$$U=\begin{pmatrix}
2 & 1 & 3 \\
0 & \frac{3}{2} & -\frac{23}{2} \\
0 & 0 & \frac{52}{3}
\end{pmatrix}\;\;\;\;\;\;\;\;
L=\begin{pmatrix}
1 & 0 & 0 \\
\frac{11}{2} & 1 & 0 \\
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}$$

In [8]:
U = np.array([[2, 1, 3], [0, 3/2, -23/2], [0, 0, 52/3]])
L = np.array([[1, 0, 0], [11/2, 1, 0], [9/2, 7/3, 1]])
np.dot(L, U)

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]])

Решаю систему:  
$$Ly=b$$
$$\begin{cases}
y_1=1 \\
\frac{11}{2}y_1+y_2=-6 \\
\frac{9}{2}y_1+\frac{7}{3}y_2+y_3=-5
\end{cases}$$
$$y_1=1$$
$$y_2=-6-\frac{11}{2}=-\frac{23}{2}$$
$$y_3=-5-\frac{9}{2}+\frac{7}{3}\cdot\frac{23}{2}=\frac{52}{3}$$
Теперь решаю систему:  
$$Ux=y$$
$$\begin{cases}
2x_1+x_2+3x_3=1 \\
\frac{3}{2} x_2-\frac{23}{2} x_3=-\frac{23}{2} \\
\frac{52}{3} x_3=\frac{52}{3}
\end{cases}$$
$$\frac{3}{2}x_2-\frac{23}{2}=-\frac{23}{2}\,\,\, \rightarrow\,\,\, \frac{3}{2}x_2=0\,\,\, \Rightarrow x_2=0$$
$$2x_1+0+3=1\,\,\, \rightarrow\,\,\, 2x_1=-2\,\,\, \Rightarrow x_1=-1$$
### $$x_1=-1,\; x_2=0,\; x_3=1$$

Подставляю получившиеся значения в изначальную систему уравнений для проверки:
$$\begin{cases}
2\cdot (-1)+0+3 \cdot 1=-2+3=1 \\
11 \cdot (-1)+7 \cdot 0+5\cdot 1=-11+5=-6 \\
9\cdot (-1)+8 \cdot 0+4 \cdot 1=-9+4=-5
\end{cases}$$
Получились тождества, следовательно корни найдены верно.

In [9]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
print(f'Корни системы уравнений: {np.around(scipy.linalg.solve(a, b), 2)}')

Корни системы уравнений: [-1.  0.  1.]


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произвожу разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50-25}=\sqrt{25}=5$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5} (-15-(-5)\cdot 5)=\frac{1}{5}(-15+25)=\frac{10}{5}=2$$
$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3$$

Получил матрицы:
$$L=\begin{pmatrix}
9 & 0 & 0 \\
-5 & 5 & 0 \\
5 & 2 & 3
\end{pmatrix}\;\;\;\;\;
L^T=\begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2 \\
0 & 0 & 3
\end{pmatrix}$$

Решаю систему $Ly=b$:
$$\begin{cases}
9y_1=531 \\
-5y_1+5y_2=-460 \\
5y_1+2y_2+3y_3=193
\end{cases}$$
$$y_1=59$$
$$5y_2=-460+295=-165\,\,\, \Rightarrow\,\,\, y_2=-33$$
$$3y_3=193-295+66=-36\,\,\, \Rightarrow\,\,\, y_3=-12$$

Решаю систему $L^T=y$:
$$\begin{cases}
9x_1-5x_2+5x_3=59 \\
5x_2+2x_3=-33 \\
3x_3=-12
\end{cases}$$
$$x_3=-4$$
$$5x_2-33+8=-25\,\,\, \Rightarrow\,\,\, x_2=-5$$
$$9x_1=59-25+20=54\,\,\, \Rightarrow\,\,\, x_1=6$$
### $$x_1=6,\; x_2=-5,\; x_3=-4$$

Подставляю получившиеся значения в изначальную систему уравнений для проверки:
$$\begin{cases}
81\cdot 6-45\cdot (-5)+45\cdot (-4)=486+225-180=531 \\
-45\cdot 6+50\cdot (-5)-15\cdot (-4)=-270-250+60=-460 \\
45\cdot 6-15\cdot (-5)+38\cdot (-4)=270+75-152=193
\end{cases}$$
Получились тождества, следовательно корни найдены верно.

In [12]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])
scipy.linalg.solve(a, b)

array([ 6., -5., -4.])