### Практическое задание к уроку 5
#### Методичка 8

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [3]:
U, s, W = np.linalg.svd(A)
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [4]:
# Проверяю на ортогональность получившуюся матрицу U
np.dot(U, U.T)

array([[ 1.,  0.,  0.,  0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1., -0.,  0.],
       [ 0., -0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  1.]])

In [5]:
# Транспонирую получившуюся матрицу W, чтобы получить матрицу V
V = W.T
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [6]:
# Проверяю на ортогональность матрицу V
np.dot(V, V.T)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [7]:
# Преобразовываю в матрицу D получившийся вектор s
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [8]:
# Провожу проверку
np.dot(np.dot(U, D), V.T)

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

После перемножения матриц $UDV^{T}$ получилась изначальная матрица $A$. Следовательно сингулярное разложение заданной матрицы было произведено верно.

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму  

Евклидова норма матрицы равна максимальному сингулярному числу $\mu_{max}$. Т.к сингулярные числа в матрице $D$ располагаются в порядке убывания, то Евклидова норма матрицы будет равна элементу $\mu_1$ или элементу $d_{11}$.

In [9]:
print(f'Евклидова норма матрицы: {D[0, 0]:.2f}')

Евклидова норма матрицы: 8.82


    б) норму Фробениуса.
Норма Фробениуса равна квадратному корню из суммы квадратов сингулярных чисел $\mu$ матрицы $D$.


In [10]:
print(f'Норма Фробениуса матрицы: {np.sqrt(np.sum(D ** 2)):.2f}')

Норма Фробениуса матрицы: 11.05
